extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_Transparent_lights;
extern Lights1 bob_dl_Island_lights;
extern Lights1 bob_dl_dirt_lights;
extern Lights1 bob_dl_grass_lights;
extern Lights1 bob_dl_side_grass_lights;
extern u8 bob_dl_SUPER_MARIO_64_AEF22277_0_2_all_ci8[];
extern u8 bob_dl_SUPER_MARIO_64_AEF22277_0_2_all_ci8_pal_rgba16[];
extern u8 bob_dl_SUPER_MARIO_64_215CE254_0_2_all_ci8[];
extern u8 bob_dl_SUPER_MARIO_64_215CE254_0_2_all_ci8_pal_rgba16[];
extern u8 bob_dl_SUPER_MARIO_64_F3B23497_0_2_all_ci8[];
extern u8 bob_dl_SUPER_MARIO_64_F3B23497_0_2_all_ci8_pal_rgba16[];
extern Vtx bob_dl_Death_Plane_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_Death_Plane_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Island_mesh_layer_1_vtx_0[9];
extern Gfx bob_dl_Island_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Terrain_mesh_layer_1_vtx_0[128];
extern Gfx bob_dl_Terrain_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Terrain_mesh_layer_1_vtx_1[405];
extern Gfx bob_dl_Terrain_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Terrain_mesh_layer_1_vtx_2[106];
extern Gfx bob_dl_Terrain_mesh_layer_1_tri_2[];
extern Gfx mat_bob_dl_Transparent[];
extern Gfx mat_bob_dl_Island[];
extern Gfx mat_revert_bob_dl_Island[];
extern Gfx mat_bob_dl_dirt[];
extern Gfx mat_revert_bob_dl_dirt[];
extern Gfx mat_bob_dl_grass[];
extern Gfx mat_revert_bob_dl_grass[];
extern Gfx mat_bob_dl_side_grass[];
extern Gfx mat_revert_bob_dl_side_grass[];
extern Gfx bob_dl_Death_Plane_mesh_layer_5[];
extern Gfx bob_dl_Island_mesh_layer_1[];
extern Gfx bob_dl_Terrain_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
